"""empty message

Revision ID: 1beb1fed2d9a
Revises: 
Create Date: 2024-01-17 14:56:25.978095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1beb1fed2d9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
